apiVersion: v1
kind: Service
metadata:
  name: bookservice
spec:
  type: NodePort
  selector:
    app: testserver
  ports:
    - protocol: TCP
      port: 3200
      nodePort: 30017
      targetPort: 8080