apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testdeploy
  name: bookdeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testserver
  template:
    metadata:
      labels:
        app: testserver
    spec:
      containers:
        - image: sabbir70/api-bookserver
          name: testserver
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP